.TH BLKZONECMD 5 "March 2016" "util-linux" "System Administration"
.SH NAME
blkzonecmd \- report zones on a device
.SH SYNOPSIS
.B blkzonecmd
[options]
.RB [ \-z
.IR zone ]
.I [\-o] or [\-c] or [\-r]
.I device
.SH DESCRIPTION
.B blkzonecmd
is used to modify the state of a zone.  This is useful for
zoned devices that support the ZAC or ZBC command set.
Unlike
.BR sg_zone (8) ,
this command is can be used on any block device.
.PP
By default,
.B blkzonecmd
will open the zone at the start of the block device. Options may be used to
modify this behavior based on the starting zone or size of the report,
as explained below.
.PP
The
.I device
argument is the pathname of the block device.
.PP
.SH OPTIONS
The
.I zone
argument may be followed by the multiplicative suffixes KiB (=1024),
MiB (=1024*1024), and so on for GiB, TiB, PiB, EiB, ZiB and YiB (the "iB" is
optional, e.g., "K" has the same meaning as "KiB") or the suffixes
KB (=1000), MB (=1000*1000), and so on for GB, TB, PB, EB, ZB and YB.
.TP
.BR \-z , " \-\-zone \fIoffset"
Byte offset into the device on which to perform the zone command.
The provided value will be aligned to the device sector size.
The default value is zero.
.TP
.BR \-o , " \-\-open"
Send an Open Zone command.
.TP
.BR \-c , " \-\-close"
Send an Close Zone command.
.TP
.BR \-r , " \-\-reset"
Send a Reset Zone command. On success all data in the zone will be
deleted.
.TP
.BR \-a , " \-\-ata"
Issue ATA passthrough commands to the connected device. This option is to
enable retrieving zone reports from SATA devices connected via SAS HBA's
which have old firmware and will not translate ZBC commands to ZAC commands
internally.
.B blkzonecmd.
.TP
.BR \-v , " \-\-verbose"
Display the aligned values of
.I zone
.TP
.BR \-V , " \-\-version"
Display version information and exit.
.TP
.BR \-h , " \-\-help"
Display help text and exit.
.SH AUTHOR
.MT shaun.tancheff@seagate.com
Shaun Tancheff
.ME
.SH SEE ALSO
.BR sg_zone (8)
.SH AVAILABILITY
The blkzonecmd command is part of the util-linux package and is available
.UR ftp://\:ftp.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
